return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    -- event = "UIEnter",
    -- lazy = false,
    priority = 1000000,
    opts = {},
    config = function()
      require("catppuccin").setup({
        integrations = { blink_cmp = true },
        highlight_overrides = {
          mocha = {
            WinSeparator = { fg = "#1e1e2f" },
            Statusline = { fg = "#cdd6f4", bg = "#1e1e2f" },
            AvanteSidebarNormal = { fg = "#cdd6f4", bg = "#1e1e2f" },
            AvantePromptInputBorder = { fg = "#cdd6f4", bg = "#1e1e2f" },
            AvanteSidebarWinHorizontalSeparator = { fg = "#1e1e2f", bg = "#1e1e2f" },
            AvanteSidebarWinSeparator = { fg = "#1e1e2f", bg = "#1e1e2f" },
            -- Normal         xxx guifg=#cdd6f4 guibg=#1e1e2f
            --- Math in md
            Conceal = { fg = "#89b4fa", bg = "" },
            -- ["@conceal"] = { fg = "#89b4fa" },
            -- ["@markup.math"] = { fg = "" },
            -- ["@text.math"] = { fg = "" },
            -- ["@markup.link.label.markdown_inline"] = { fg = "#7dc4e4" },
            -- SnacksImageMath = { fg = "#eba0ac" },
            -- --- Math in tex
            texEnvArgName = { fg = "#9399b3" },
            texOptEqual = { fg = "#7dc4e4" },
            texMathDelim = { fg = "#f9e2af" },
            ["@spell.latex"] = { fg = "#cdd6f4" },
            ["@spell.markdown"] = { fg = "#cdd6f4" },
            texMathSymbol = { fg = "#89b4fa" },
            texFileArg = { fg = "#b4befe" },
            texPartConcArgTitle = { fg = "#89b4fa", bold = true },
            texCmdRef = { fg = "#7dc4e4" },
            texCmdEnv = { fg = "#b4befe", italic = true },
            texCmdInput = { fg = "#7dc4e4", italic = true },
            texCmdClass = { fg = "#eba0ac", italic = true, bold = true },
            NoteEngDefinition = { fg = "#b4befe", italic = true },
            NoteEngWord = { fg = "#7dc4e4", bold = true },
            -- texRefArg = { fg = "#f5c2e7", bold = true },
            -- Function = { fg = "" },
            -- -- Delimiter = { fg = "" },
            -- Include = { fg = "" },
            -- Label = { fg = "" },
            -- texMathDelimZoneTD = { fg = "" },
            Special = { fg = "" },
            -- ["@function.macro"] = { fg = "" },
            -- ["@variable.parameter"] = { fg = "" },
            -- ["@string.special.path.latex"] = { fg = "" },
            --- Telescope
            TelescopeeTitle = { fg = "#1e1e2e", bg = "#eba0ac" },
            -- TelescopePromptTitle = { fg = "#1e1e2e", bg = "#f5c2e7", italic = true, bold = true },
            -- TelescopePreviewTitle = { fg = "#1e1e2e", bg = "#b4befe", bold = true },
            -- TelescopeResultsTitle = { fg = "#1e1e2e", bg = "#fab387", bold = true },
            TelescopeNormal = { fg = "#cdd6f4", bg = "#181825" },
            -- TelescopePrompt = { fg = "#f5c2e7", bg = "#1e1e2e" },
            TelescopeBorder = { fg = "#181825", bg = "#181825" },
            WhichKeyBorder = { fg = "#181825", bg = "#181825" },
            -- WhichKeyTitle = { fg = "#b4befe", bg = "#181825" },
            BlinkCmpMenuSelection = { fg = "#1e1e2e", bg = "#b4befe", italic = true, bold = true },
            -- CmpItemAbbrDeprecated = { fg = "#b4befe", strikethrough = true },
            -- CmpItemAbbrMatch = { fg = "#b4befe" },
            -- CmpItemAbbrMatchFuzzy = { fg = "#b4befe" },
            -- CmpItemAbbrDefault = { fg = "#b4befe" },
            -- CmpItemAbbr = { fg = "#bac2de" },
          },
          lattie = {
            -- Normal         xxx guifg=#4c4f69 guibg=#ffffff
            --- Math in md
            -- Conceal = { fg = "#d3869b", bg = "" },
            -- ["@markup.math"] = { fg = "#4c4f69" },
            -- ["@text.math"] = { fg = "#4c4f69" },
            -- ["@markup.link.label.markdown_inline"] = { fg = "#458588" },
            -- SnacksImageMath = { fg = "#cc241d" },
            --- Math in tex
            -- texEnvArgName = { fg = "#7c6f64" },
            -- texOptEqual = { fg = "#458588" },
            -- texMathDelim = { fg = "#d79921" },
            -- texFileArg = { fg = "#83a598" },
            -- texPartConcArgTitle = { fg = "#b16286", bold = true },
            -- texCmdRef = { fg = "#458588" },
            -- texCmdEnv = { fg = "#83a598", italic = true },
            -- texCmdInput = { fg = "#458588", italic = true },
            -- texCmdClass = { fg = "#cc241d", italic = true, bold = true },
            -- texRefArg = { fg = "#d3869b", bold = true },
            -- Function = { fg = "#4c4f69" },
            -- Include = { fg = "#4c4f69" },
            -- Label = { fg = "#4c4f69" },
            -- texMathDelimZoneTD = { fg = "#4c4f69" },
            -- ["@function.macro"] = { fg = "#4c4f69" },
            -- ["@variable.parameter"] = { fg = "#4c4f69" },
            -- ["@string.special.path.latex"] = { fg = "#4c4f69" },
            --- Telescope
            TelescopeeTitle = { fg = "#ffffff", bg = "#cc241d" },
            TelescopePromptTitle = { fg = "#ffffff", bg = "#d3869b", italic = true, bold = true },
            TelescopePreviewTitle = { fg = "#ffffff", bg = "#83a598", bold = true },
            TelescopeResultsTitle = { fg = "#ffffff", bg = "#fabd2f", bold = true },
            TelescopeNormal = { fg = "#4c4f69", bg = "#f9f5d7" },
            TelescopePrompt = { fg = "#d3869b", bg = "#ffffff" },
          },
        },
      })
      vim.cmd("colorscheme catppuccin")
    end,
  },
}
